[package]
name = "dxlib-rs-macro"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.101", features = ["full"] }
thiserror = "2.0.12"
[lib]
proc-macro = true
